version = 0.1
[default.deploy.parameters]
stack_name = "PersonalPhotoGalleryStack"
resolve_s3 = true
s3_prefix = "PersonalPhotoGalleryStack"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
parameter_overrides = "DeployType=\"dev\" DBMasterUsername=\"admin\" VpcId=\"vpc-0f1c4d73af9f53a58\""
disable_rollback = true
