AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description:  Pictorialdiary Backend Application for development

Parameters:
  DeployType:
      Type: String
      AllowedValues: [dev, stag, prod]
      Default: dev
      Description: Deploy Type
  DBMasterUsername:
    Type: String
    Description: The master username for the database.
  DBMasterPassword:
    Type: String
    NoEcho: true
    Description: The master password for the database.
  VpcId:
    Type: String
    Description: The ID of VPC.

Resources:
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        openapi: "3.0.0"
        info:
          version: "1.0.0"
        paths:
          /users/register:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RegisterUserFunction.Arn}/invocations
          /users/confirm:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConfirmUserFunction.Arn}/invocations
          /users/login:
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LoginUserFunction.Arn}/invocations
          /users/logout:
            post:
              x-amazon-apigateway-integration:
                httpMethod: GET
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LogOutUserFunction.Arn}/invocations

  RegisterUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: aws/cmd/user/register
      Handler: main.go
      Runtime: go1.x
      Events:
        RegisterUser:
          Type: Api
          Properties:
            Path: /users/register
            Method: post
  ConfirmUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: aws/cmd/user/confirm 
      Handler: main.go
      Runtime: go1.x
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            Path: /users/confirm
            Method: post
  LoginUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: aws/cmd/user/login 
      Handler: main.go
      Runtime: go1.x
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            Path: /users/login
            Method: post
  LogOutUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: aws/cmd/user/logout 
      Handler: main.go
      Runtime: go1.x
      Events:
        ConfirmUser:
          Type: Api
          Properties:
            Path: /users/logout
            Method: get

  DynamoStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/dynamo.yml
      Parameters:
        DeployType: !Ref DeployType
  S3Stack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      Location: stacks/s3.yml
      Parameters:
        DeployType: !Ref DeployType
  AuroraStack:
    Type: AWS::Serverless::Application
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Location: stacks/rds.yml
      Parameters:
        DeployType: !Ref DeployType
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterPassword: !Ref DBMasterPassword
        VpcId: !Ref VpcId